[package]
name = "FixedPoint64"
version = "1.0.0"

[addresses]
fixed_point64 = "304775da9aa9634ef942a3988673632a382e9e6994983fdf7dba5e175bcd615a"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"
